//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはツールによって生成されました。
//     ランタイム バージョン:4.0.30319.42000
//
//     このファイルへの変更は、以下の状況下で不正な動作の原因になったり、
//     コードが再生成されるときに損失したりします。
// </auto-generated>
//------------------------------------------------------------------------------

namespace YokaiSearcher.Properties {
    using System;
    
    
    /// <summary>
    ///   ローカライズされた文字列などを検索するための、厳密に型指定されたリソース クラスです。
    /// </summary>
    // このクラスは StronglyTypedResourceBuilder クラスが ResGen
    // または Visual Studio のようなツールを使用して自動生成されました。
    // メンバーを追加または削除するには、.ResX ファイルを編集して、/str オプションと共に
    // ResGen を実行し直すか、または VS プロジェクトをビルドし直します。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   このクラスで使用されているキャッシュされた ResourceManager インスタンスを返します。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("YokaiSearcher.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   すべてについて、現在のスレッドの CurrentUICulture プロパティをオーバーライドします
        ///   現在のスレッドの CurrentUICulture プロパティをオーバーライドします。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   ANKAAIT0.M.9G!
        ///GMKAAJSMW.!8G!
        ///GHAAEKNZ!!NY4-
        ///AGWADZUYT5SYU-
        ///GMAABIR..UUW0-
        ///AKKAE5!4ZNWN.M
        ///AABINGZ-.!97NG
        ///ANKADNS-87E!N-
        ///AHGWENN.M79DT0
        ///GNAABN!Z-J7.D!
        ///ANGABNU!7Y0I.M
        ///GDWADB0U9.G3YU
        ///ADHAR0U!MM.N!J
        ///G9AADZZM8MI!G.
        ///HD7AKD0Z-GM5N.
        ///AYAAN-N3!GJM-!
        ///GKAAEK-G!K!8ZZ
        ///AIKAM!S-6.GN9G
        ///G5BKATMN-R!2PT
        ///GDWADU6GK8UU4-
        ///GIAAG8ZKT9NZM!
        ///EKAAG.MIG8!Y!Z
        ///AABI09GU0.KM.M
        ///AK5AGNE.I-0K9-
        ///AHGAM69GK--G!.
        ///EBAAN!8N-9JMU-
        ///AHGAM.INB!9U.!
        ///ADG5BR.TJ8YUN4
        ///ANKAE4.T7IMN.0
        ///GMWAB..8BSSUK-
        ///DGWAD..S6TSPU-
        ///H9AAMK.54GMZ.M
        ///GABWGURNN374YU
        ///APABGN!!NK9NZZ
        ///EK [残りの文字列は切り詰められました]&quot;; に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string passwords {
            get {
                return ResourceManager.GetString("passwords", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ver.1.09 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string VersionText {
            get {
                return ResourceManager.GetString("VersionText", resourceCulture);
            }
        }
    }
}
